Use pre-commit for linting.
gocept/gobre.recipe.template pull request #4
Opened 2021-01-21 11:18 UTC by sallner

Let's use pre-commit for linting now. In case of a failure it is typically fixed (isort, flake8) and the commit is aborted and can be (re-)viewed again.

2021-01-22 07:18 UTC, icemac requested changes
LGTM besides `add-trailing-comma`.
It might be okay for lists but not for function calls.

2021-01-22 07:18 UTC, icemac commented on gobre/recipe/template/__init__.py
> +                "The number of template and target files must match",
Is it possible to disable this style rule? IMHO it is one of the silliest rules to have a trailing comma in function calls as this is totally redundant and we have good enough diff tools now so there is no need to keep this old rule of possibly reducing future diffs.

2021-01-22 07:18 UTC, icemac commented on .pre-commit-config.yaml
> +          - id: add-trailing-comma
I do not like it at all and I do not buy the argumentation why it might be useful.

2021-01-25 07:44 UTC, sallner commented
I will remove the trailing-comma checker.

2021-01-25 12:25 UTC, sallner commented
I updated the commits to not use the trainling-comma fixer.

2021-01-25 12:29 UTC, icemac approved these changes
LGTM.

2021-01-25 12:42 UTC, merged